version: '3'

services:
  app:
    build:
      context: sample-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  netshoot:
    image: nicolaka/netshoot
    command: sleep infinity
    network_mode: "service:app"
